### ISSUE TITLE
East Style Display has problems

### ISSUE THREAD

**Issue by mahen3d** [kunjara/jyotish#2]
When i checked the output for following birthrate, east style and north style display has problems. (East style is incorrectly rendered)

$datetime_data = new DateTime('1987-09-09 14:27:00', new DateTimeZone('Asia/Colombo'));
$locality_data = array(
    'longitude' => 79.51,
    'latitude'  => 6.53,
    'altitude'  => 0.01
);

**Comment by astrosanthosh** [comment]
Please let me know how to use it

**Comment by mahen3d** [comment]
still no documentation on this how to use it, i just dig it using reverse engineering techniques, plus i had to correct quite a lot of original coding issues like !empty, you need to combine this with the jyothish-draw and swetest to get something working on.

**Comment by astrosanthosh** [comment]
oh ok, thanks

**Comment by rajeshkannansattva** [comment]
Hi Mahen,

Can you share the document if you have or can you send the contact details of you.
